alloy:
  configMap:
    content: |-
      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.relabel "pods" {
        targets = discovery.kubernetes.pods.targets
        rule {
          action        = "replace"
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }
        rule {
          action        = "replace"
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod_name"
        }
        rule {
          action        = "replace"
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container_name"
        }
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.relabel.pods.output
        forward_to = [loki.process.add_new_label.receiver]
      }

      loki.process "add_new_label" {
        stage.logfmt {
          mapping = {
            "vaisseau" = "vaisseau",
            "pilote"  = "pilote",
            "message" = "message",
          }
        }

        stage.labels {
          values = {
            "vaisseau" = "vaisseau",
            "pilote"  = "pilote",
            "message" = "message",
          }
        }

        forward_to = [loki.relabel.log_relabel.receiver]
      }

      loki.relabel "log_relabel" {
        forward_to = [loki.write.grafana_loki.receiver]
      }

      loki.write "grafana_loki" {
        endpoint {
          url = "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
        }
      }
