alertmanager:
  config:
    global:
      resolve_timeout: 1m
      smtp_smarthost: 'mailhog:1025'
      smtp_from: 'alertmanager@loki.local'
      smtp_require_tls: false 
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 5m
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: 'hamdi@loki.local'
